// Artist Actions

export const GET_ALL_MACHINES_REQUEST = 'GET_ALL_MACHINES_REQUEST';
export const GET_ALL_MACHINES_SUCCESS = 'GET_ALL_MACHINES_SUCCESS';
export const GET_ALL_MACHINES_ERROR = 'GET_ALL_MACHINES_ERROR';

export const GET_MACHINES_BY_ID_REQUEST = 'GET_MACHINES_BY_ID_REQUEST';
export const GET_MACHINES_BY_ID_SUCCESS = 'GET_MACHINES_BY_ID_SUCCESS';
export const GET_MACHINES_BY_ID_ERROR = 'GET_MACHINES_BY_ID_ERROR';

export const UPDATE_MACHINE_REQUEST = 'UPDATE_MACHINE_REQUEST';
export const UPDATE_MACHINE_SUCCESS = 'UPDATE_MACHINE_SUCCESS';
export const UPDATE_MACHINE_ERROR = 'UPDATE_MACHINE_ERROR';

export const WS_UPDATE_MACHINES_DATA = 'WS_UPDATE_MACHINES_DATA';